name: CI/CD - TingTing to EC2

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/tingting-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract meta (tags & labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail

            APP_DIR=/tingting
            mkdir -p "$APP_DIR"
            cd "$APP_DIR"

            # compose.yaml 생성(최초 1회) 또는 유지
            if [ ! -f compose.yaml ]; then
              cat <<'EOL' > compose.yaml
services:
  backend:
    image: ${REGISTRY_IMAGE}:${TAG}
    container_name: tingting-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
EOL
            fi

            # .env 존재 확인
            if [ ! -f .env ]; then
              echo "ERROR: .env not found on EC2 at $APP_DIR/.env" >&2
              exit 1
            fi

            # .env의 레지스트리/태그 갱신
            if grep -q '^REGISTRY_IMAGE=' .env; then
              sed -i "s|^REGISTRY_IMAGE=.*|REGISTRY_IMAGE=${{ env.IMAGE_NAME }}|" .env
            else
              echo "REGISTRY_IMAGE=${{ env.IMAGE_NAME }}" >> .env
            fi

            if grep -q '^TAG=' .env; then
              sed -i "s|^TAG=.*|TAG=latest|" .env
            else
              echo "TAG=latest" >> .env
            fi

            # 최신 이미지 풀 & 재기동
            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            docker compose pull
            docker compose up -d
            docker image prune -f
            docker compose ps
